### ISSUE TITLE
You shouldn't just do nothing when catching an Exception

### ISSUE THREAD

**Issue by msaccone** [bruno-garcia/log4net.ElasticSearch#111]
https://github.com/jptoto/log4net.ElasticSearch/blob/c4e3c80d4388fcdb6dfb49cacf4afc3756159a08/src/log4net.ElasticSearch/Repository.cs#L45

I've been working with this plugin, and faced a certificate self signed issue.

I didn't have any clue because of this void catch.

**Comment by bruno-garcia** [comment]
Agreed. We should let it bubble up. The Appender actually supresses all exceptions while logging them to `log4net.Core`

**Comment by bruno-garcia** [comment]
Published as [2.6.0-preview](https://www.nuget.org/packages/log4net.ElasticSearch/2.6.0-preview)
