### ISSUE TITLE
docker problem

### ISSUE THREAD

**Issue by indexlang** [bruno-garcia/log4net.ElasticSearch#113]
when I use the nuget package in windows 10,there is no problem,
but when I publish my project to docker ,they cannot work well and have no error info.

**Comment by bruno-garcia** [comment]
If it's working from Windows, and you didn't change the configuration at all when creating the docker image it's more likely it's a networking issue. Where the app can't reach the indexer.

It's hard to help you in this case. Specially without any repro. Feel free to reopen if you can provide some small reproducible.
