### ISSUE TITLE
Can't see logs even there is no error 

### ISSUE THREAD

**Issue by fightlikeagirl** [bruno-garcia/log4net.ElasticSearch#119]
Hello, I followed the settings that you show. I can't see the logs .
This is config file App.config: (.Net Framework 4.6)

```
<?xml version="1.0" encoding="utf-8"?>
<configuration> 
  <configSections>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net" />
  </configSections>
  <appSettings>
    <add key="log4net.Internal.Debug" value="true"/>
  </appSettings>
  <system.diagnostics>
    <trace autoflush="true">
      <listeners>
        <add
            name="textWriterTraceListener"
            type="System.Diagnostics.TextWriterTraceListener"
            initializeData="C:\temp\log4net.txt" />
      </listeners>
    </trace>
  </system.diagnostics>
 
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
  <log4net>
    <appender name="ElasticSearchAppender" type="log4net.ElasticSearch.ElasticSearchAppender, log4net.ElasticSearch">
      <!-- for .NET 40 <appender name="ElasticSearchAppender" type="log4net.ElasticSearch.ElasticSearchAppender, log4net.ElasticSearch.Net40">-->
      <connectionString value="Scheme=https;Server=localhost;Index=log;Port=9201;rolling=false" />
      <lossy value="false" />
      <evaluator type="log4net.Core.LevelEvaluator">
        <threshold value="ERROR" />
      </evaluator>
      <bufferSize value="1" />
    </appender>
    <root>
      <level value="ALL" />
      <appender-ref ref="ElasticSearchAppender" />
    </root>
  </log4net>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

```
AssemlyInfo.cs :
`[assembly: log4net.Config.XmlConfigurator(Watch = true)]
[assembly: RepositoryAttribute("NetTweetLog")]`

and log4net.txt for logs : 
`\log4net.dll]. (.NET Runtime [4.0.30319.42000] on Microsoft Windows NT 6.2.9200.0)
log4net: defaultRepositoryType [log4net.Repository.Hierarchy.Hierarchy]
log4net: Creating repository for assembly [NetTweetLog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
log4net: Assembly [NetTweetLog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] Loaded From [E:\e\e\konsol\NetTweetLogElastic\NetTweetLog\bin\Debug\NetTweetLog.exe]
log4net: Assembly [NetTweetLog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] using repository [NetTweetLog] and repository type [log4net.Repository.Hierarchy.Hierarchy]
log4net: Creating repository [NetTweetLog] using type [log4net.Repository.Hierarchy.Hierarchy]
log4net: configuring repository [NetTweetLog] using file [E:\e\e\konsol\NetTweetLogElastic\NetTweetLog\bin\Debug\NetTweetLog.exe.Config] watching for file updates
log4net: configuring repository [NetTweetLog] using file [E:\e\e\konsol\NetTweetLogElastic\NetTweetLog\bin\Debug\NetTweetLog.exe.Config]
log4net: configuring repository [NetTweetLog] using stream
log4net: loading XML configuration
log4net: Configuring Repository [NetTweetLog]
log4net: Configuration update mode [Merge].
log4net: Logger [root] Level string is [ALL].
log4net: Logger [root] level set to [name="ALL",value=-2147483648].
log4net: Loading Appender [ElasticSearchAppender] type: [log4net.ElasticSearch.ElasticSearchAppender, log4net.ElasticSearch]
log4net: Setting Property [ConnectionString] to String value [Scheme=https;Server=localhost;Index=log;Port=9201;rolling=false]
log4net: Setting Property [Lossy] to Boolean value [False]
log4net: Setting Property [Threshold] to Level value [ERROR]
log4net: Setting Property [Evaluator] to object [log4net.Core.LevelEvaluator]
log4net: Setting Property [BufferSize] to Int32 value [1]
log4net: Created Appender [ElasticSearchAppender]
log4net: Adding appender named [ElasticSearchAppender] to logger [root].
log4net: Hierarchy Threshold []` 
Thank you for any help.

**Comment by fightlikeagirl** [comment]
I solved it from your example . Sorry

**Comment by LuciaVeldera** [comment]
How can you solve it? I struggle the same issue as you but I don't know where to look at. @fightlikeagirl

**Comment by danammeansbear** [comment]
what was the issue?
