### ISSUE TITLE
Httpclient - httpresponse issue

### ISSUE THREAD

**Issue by koderi-dp** [bruno-garcia/log4net.ElasticSearch#121]
Hi,

when using this library in net core console app 2.2, i get exception

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpWebResponse'.

i think problem is in this part (httpResponse.Close)

``` 
              var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
              httpResponse.Close();
              if (httpResponse.StatusCode != HttpStatusCode.Created && httpResponse.StatusCode != HttpStatusCode.OK)

```
why not change it to

```
  using (var httpResponse = (HttpWebResponse) httpWebRequest.GetResponse())
                {
                    if (httpResponse.StatusCode != HttpStatusCode.Created && httpResponse.StatusCode != HttpStatusCode.OK)
                    {
                        throw new WebException("Failed to post {0} to {1}.".With(postBody.ToString(), uri));
                    }
                }

```
then it is working

**Comment by bruno-garcia** [comment]
@koderi-dp do you have a stack trace so we can point to the exact line number?
You suggest by _then it is working_ because you've made that change and verified the fix?

You could add [Sentry](https://github.com/getsentry/sentry-dotnet) to your app so errors would be sent there even if your logging isn't working.

**Comment by koderi-dp** [comment]
> @koderi-dp do you have a stack trace so we can point to the exact line number?
> You suggest by _then it is working_ because you've made that change and verified the fix?
> 
> You could add [Sentry](https://github.com/getsentry/sentry-dotnet) to your app so errors would be sent there even if your logging isn't working.

Hi, exception was in line where status code is checked, 
 if (httpResponse.StatusCode != HttpStatusCode.Created && httpResponse.StatusCode != HttpStatusCode.OK)

I had to download the source change it like in sugestion (put it in using without manualy closing the connection) and its working without issues, it looks if you acces status code prop of disposed response it will throw exception, didnt go into reflection of source code, maybe connected to net standard or net core version

**Comment by bruno-garcia** [comment]
Makes sense. Would you open a PR with the fix for this?

**Comment by koderi-dp** [comment]
> Makes sense. Would you open a PR with the fix for this? Happy to accept PRs

Sure

**Comment by koderi-dp** [comment]
#122 created
