### ISSUE TITLE
Please sign the assembly strong name

### ISSUE THREAD

**Issue by KagurazakaNyaa** [bruno-garcia/log4net.ElasticSearch#126]
An non-strong-named assembly cannot be referenced by a strong-named assembly, and the current assembly in NuGet is a non-strong-named assembly.

**Comment by KagurazakaNyaa** [comment]
Please see [here](https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-use-strong-named) for details.

**Comment by bruno-garcia** [comment]
I'm not planning to strong sign the assembly at the moment but you can do it yourself:

https://github.com/dsplaisted/strongnamer

**Comment by KagurazakaNyaa** [comment]
It works, thank you.
