### ISSUE TITLE
Error - Could not create SSL/TLS secure channel when using Azure Elastic-Search

### ISSUE THREAD

**Issue by adamfarmer0** [bruno-garcia/log4net.ElasticSearch#137]
![image](https://user-images.githubusercontent.com/77245567/167837309-9d644a0f-daf6-4e4b-87b1-5413ef6dd8ce.png)

I am getting this error when trying to connect to azure elastic-search.

my config:
```
<log4net>
<appender name="ElasticSearchAppender" type="log4net.ElasticSearch.ElasticSearchAppender, log4net.ElasticSearch">
  <connectionString value="Scheme=https;User=*******;Pwd=********;Server=commercial-***-***.es.westeurope.azure.elastic-cloud.com;Index=logs-2022;Port=443;rolling=true;" />
</appender>
<root>
  <level value="ALL" />
  <appender-ref ref="ElasticSearchAppender" />
</root>
</log4net>
```

Can anyone tell me how can I fix this? It's probably some certificate issue, but I can't figure it out.

**Comment by adamfarmer0** [comment]
I have fixed it by adding:
```
          ServicePointManager.Expect100Continue = true;
          ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```
in Startup.cs, inside Configuration method. For anyone that gets this error, this is the solution.

**Comment by bruno-garcia** [comment]
Nice. thanks for sharing the fix @adamfarmer0
