### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by discoverer-official** [bruno-garcia/log4net.ElasticSearch#140]
@bruno-garcia  When will be released 2.6.0? and other improvements? repository look as dead (((

**Comment by bruno-garcia** [comment]
@discoverer-official I could make a release but I haven't been using the project so I can't test it or give feedback. Is the preview working for you?

**Comment by danammeansbear** [comment]
I would also be interested to see what it would take to get this working!

**Comment by bruno-garcia** [comment]
@danammeansbear what's not working? There are not bug fixes unshipped.
But also, happy to take PRs if there are things that need improvement for you.

**Comment by discoverer-official** [comment]
Yes, It's working for me

**Comment by danammeansbear** [comment]
having a bug where adding SSL to our server has eliminated our abilities to use the appender. We can send logs via postman and curl and even https using c# but once we tried to log using the appender, nothing makes its way to ELK. I know log4stash isnt the issue.

**Comment by bruno-garcia** [comment]
@danammeansbear any stack traces or something I can look into?

**Comment by bruno-garcia** [comment]
I see you also wrote on this ticket: https://github.com/bruno-garcia/log4net.ElasticSearch/issues/123#issuecomment-2214915575

I'll close this since I'm still here to help just didn't push updates since nothing new came up on log4net land in ages
