### ISSUE TITLE
Proxy setting support

### ISSUE THREAD

**Issue by betimer** [bruno-garcia/log4net.ElasticSearch#80]
is is possible to add proxy setting support into this appender?

e.g. <connectionString value="Server=127.0.0.1;Index=log_test;Port=9200;rolling=false;proxy=10.0.0.20:3330"/>

**Comment by jptoto** [comment]
@betimer This is a potentially good idea. I will investigate it.

**Comment by bruno-garcia** [comment]
You can define a proxy via the standard configuration (app.config or web.config) and it'll be picked up by the library.
